---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no

  pre_tasks:
    - name: Update homebrew formulas
      homebrew:
        update_homebrew: yes

  roles:
    - user
    - dev
    - rsc

  post_tasks:
    - name: Homebrew cleanup
      shell: brew cleanup
      register: result
      changed_when: result.stdout.find("This operation has freed approximately") != -1
