---
- name: Install homebrew packages
  homebrew: name={{ item }} state=present
  with_items:
    - mc
    - ranger
    - tmux
    - vifm
    - wget
    - tree
    - htop
    - nmap
    - ssh-copy-id
    - ffmpeg
    - youtube-dl
    - ncdu

- name: Caskroom taps
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - homebrew/cask

- name: Install applications
  homebrew_cask: name={{ item }} state=present
  with_items:
    - appcleaner
    - google-chrome
    - firefox
    - viber
    - skype
    - dropbox
    - keka
    # - java
    - mucommander
    - marta
    - transmission
    - mpv
#    - mplayerx
    - vlc
    - microsoft-office
    - grammarly
    - perian
    - air-video-server-hd
    - plex-media-server
    - carbon-copy-cloner
    - uninstallpkg
#    - murasaki
    # - fluid
    - telegram
    - goofy
    - whatsapp
    # - flume
    - android-file-transfer

# EOF
