---
- name: Homebrew taps
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - homebrew/science

- name: Install homebrew packages
  homebrew: name={{ item }} state=present
  with_items:
    - r
    - ag
    - ack
    - docker-clean
    - pipenv
    - pyenv
    - pyenv-virtualenv

- name: Caskroom taps
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - homebrew/cask
    - homebrew/cask-versions

- name: Install applications
  homebrew_cask: name={{ item }} state=present
  with_items:
    - rstudio
#    - octave
#    - scilab
    - iterm2
    - macvim
    - sublime-text
    - docker
    - pycharm
    # - pycharm-ce

# EOF
