---
- name: Homebrew taps
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - homebrew/services
    - pivotal/tap
    - cloudfoundry/tap

- name: Install homebrew packages
  homebrew: name={{ item }} state=present
  with_items:
    - bash-completion
    - ant
    - maven
    - gradle
    - springboot
    - ag
    - ack
    - peco
    - ctags
    - gotags
    - httpie
    - tig
    - mongodb
    - redis
    - go
    - docker
    - docker-compose
    - docker-clean
    - docker-swarm
    - docker-machine
    - node
    - android-platform-tools
    - heroku
    - editorconfig

- name: Caskroom taps
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - caskroom/cask
    - caskroom/versions

- name: Install applications
  homebrew_cask: name={{ item }} state=present
  with_items:
    - java
    - intellij-idea
    - intellij-idea-ce
    - iterm2
    - macvim
    - sublime-text
    - docker
    - paw
    - transmit
    - postman
    - sourcetree
    - skype-for-business
    - tunnelblick
    - sequel-pro
    - postgres
    - pgadmin3
    - mysqlworkbench
    - robomongo
    - studio-3t
    - virtualbox
    - vagrant
    - free-ruler
    - pencil
    # - android-studio
    - android-file-transfer
    - android-sdk
    # - slack
    - visual-studio-code

# EOF
