---
- name: Homebrew taps
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - homebrew/services
    - pivotal/tap
    - cloudfoundry/tap

- name: Install homebrew packages
  homebrew: name={{ item }} state=present
  with_items:
    - bash-completion
    - ant
    - maven
    - gradle
    # - springboot
    - ag
    - ack
    - peco
    - ctags
    - gotags
    - httpie
    - tig
    - tree
    # - mongodb
    # - redis
    - go
    - docker-clean
    # - docker-swarm
    # - docker-machine
    - pipenv
    - pyenv
    - pyenv-virtualenv
    - node
    - android-platform-tools
    # - heroku
    - editorconfig

- name: Caskroom taps
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - homebrew/cask
    - homebrew/cask-versions

- name: Install applications
  homebrew_cask: name={{ item }} state=present
  with_items:
    - java8
    - java
    - intellij-idea
    - iterm2
    - macvim
    - sublime-text
    - docker
    - paw
    - tower
    # - tower2
    - transmit
    - postman
    # - skype-for-business
    - tunnelblick
    - sequel-pro
    - postico
    - postgres
    # - mysqlworkbench
    - robo-3t
    # - studio-3t
    - virtualbox
    - vagrant
    - free-ruler
    - pencil
    # - android-studio
    - android-file-transfer
    - android-sdk
    # - visual-studio-code
    - pycharm
    # - pycharm-ce

# EOF
